### ISSUE TITLE
New failing test cases

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#10]
The following test cases fail on the new version of forte (inversion).

```
        ------------------------------------------------------------------------
        MR-DSRG-PT2-1.............................................DOES NOT MATCH
        DSRG-MRPT2-6..............................................DOES NOT MATCH
        DSRG-MRPT2-8..............................................DOES NOT MATCH
        DF-DSRG-MRPT2-2...........................................DOES NOT MATCH
        DF-DSRG-MRPT2-THREADING1..................................DOES NOT MATCH
        DF-DSRG-MRPT2-THREADING2..................................DOES NOT MATCH
        DF-DSRG-MRPT2-THREADING4..................................DOES NOT MATCH
        DISKDF-DSRG-MRPT2-THREADING1..............................DOES NOT MATCH
        DISKDF-DSRG-MRPT2-THREADING4..............................DOES NOT MATCH
        DISKDF-DSRG-MRPT2-2.......................................DOES NOT MATCH
        ACI-14....................................................DOES NOT MATCH
        ------------------------------------------------------------------------
```

**Comment by fevangelista** [comment]
Here is some more detailed info.  These test seem to differ significantly from the reference values:

- diskdf-dsrg-mrpt2-2, DSRG-MRPT2 Energy: computed value (-100.106152173) does not match (-100.107827239) to 8 decimal places.
- df-dsrg-mrpt2-2, DF-DSRG-MRPT2 energy: computed value (-100.10235967134) does not match (-100.10068472277) to 10 decimal places.
- df-dsrg-mrpt2-threading1, DSRG-MRPT2 energy: computed value (-226.85431519750) does not match (-226.85228622918) to 10 decimal places.
- df-dsrg-mrpt2-threading2, DSRG-MRPT2 energy: computed value (-226.85431519750) does not match (-226.85228622918) to 10 decimal places.
- df-dsrg-mrpt2-threading4, DSRG-MRPT2 energy: computed value (-226.85431519750) does not match (-226.85228622918) to 10 decimal places.
- diskdf-dsrg-mrpt2-threading1, DSRG-MRPT2 energy: computed value (-226.85431519751) does not match (-226.85228622918) to 10 decimal places.
- diskdf-dsrg-mrpt2-threading4, DSRG-MRPT2 energy: computed value (-226.85431519751) does not match (-226.85228622918) to 10 decimal places.
- aci-14, ACI energy: computed value (-75.5625751329) does not match (-75.4517514197) to 9 decimal places.

In these cases differences are minor, but might be worth investigating especially the first two cases:
- dsrg-mrpt2-6, DSRG-MRPT2 relaxed energy: computed value (-109.24612661379) does not match (-109.24612765688) to 10 decimal places.
- dsrg-mrpt2-8, MS-DSRG-MRPT2 energy root 0: computed value (-106.92995880759) does not match (-106.92995878367) to 10 decimal places.
- mr-dsrg-pt2-1, MR-DSRG-PT2 energy: computed value (-15.62718488929) does not match (-15.62718488892) to 10 decimal places.

**Comment by kannon92** [comment]
All the listed df codes fail because we changed how frozen core is handled.  I have to change the reference values.

**Comment by jeffschriber** [comment]
I cannot reproduce an error with ACI-14

**Comment by kannon92** [comment]
With my previous commit, these 4 are the only ones that fail on my laptop and on the cluster.  

MR-DSRG-PT2-1
DSRG-MRPT2-6
DSRG-MRPT2-8
DSRG-MRPT3-5

**Comment by fevangelista** [comment]
Just to keep @lcyyork in the loop:
These might be simply a problem with the fact that now we use the DF_BASIS_MP2 to compute the frozen core energy/operator instead of the DF_BASIS_SCF.

**Comment by lcyyork** [comment]
I am compiling the new psi4 and forte now. I am just curious, does the CASSCF energies match previous numbers?

**Comment by fevangelista** [comment]
They should.  However, we should check.  We should also do some tests to make sure that relative energies (at DF-DSRG, etc.) are consistent now that we have switched to one DF basis for post SCF methods.

**Comment by jeffschriber** [comment]
A brief update:

- MR-DSRG-PT2-1: CASSCF energies agree, CASSCF wavefunctions agree to at least 5 decimal places (that's all that are printed). First discrepancy I see is in the 10th digit of the cumulants. Final energy disagrees in the 10th digit. 

- DSRG-MRPT2-6: CASSCF energies, wfns, and the NOs all agree. First discrepancy is in the off-diagonal norm of the Fock matrix: 0.6173461790 vs 0.6443205882. 

- DSRG-MRPT2-8: Computation fails in CASSCF:
    
         Fatal Error: Average state greater than the number of roots!

- DSRG-MRPT3-5: Computation fails in CASSCF:
    
         Fatal Error: Average state greater than the number of roots!

**Comment by jeffschriber** [comment]
Thanks, York. I updated the indices for the CASSCF, and the DSRG-MRPT3-5 now passes. DSRG-MRPT2-8 still fails in a similar way to DSRG-MRPT2-6

**Comment by jeffschriber** [comment]
Another thing, CASSCF-4 sometimes fails with the following:

       ==> Starting MCSCF iterations <==                                                                                                                                                 
                                                                                                                                                                                     
            Iter         Total Energy       Delta E   Orb RMS    CI RMS  NCI NORB                                                                                                        
        @MCSCF  1:                 nan    nan  nan  0.00e+00   12    1  Initial CI                                                                                                        
        @MCSCF  2:                 nan    nan  nan  0.00e+00   12    1  TS                                                                                                                
        @MCSCF  3:                 nan    nan  nan  0.00e+00   12    1  TS                                                                                                                
        @MCSCF  4:                 nan    nan  nan  0.00e+00   12    1  TS, DIIS                                                                                                          
                                                                                                                                                                                     
    Traceback (most recent call last):                                                                                                                                                   
      File "/Users/jeffschriber/src/psi4_debug_install/bin/psi4", line 223, in <module>                                                                                                  
        exec(content)                                                                                                                                                                    
      File "<string>", line 43, in <module>                                                                                                                                              
      File "/Users/jeffschriber/src/psi4_debug_install/lib//psi4/driver/driver.py", line 447, in energy                                                                                  
        wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)                                                                                                    
      File "/Users/jeffschriber/src/psi4_debug_install/lib//psi4/driver/procedures/proc.py", line 4053,      in run_detcas                                                                    
         ciwfn = mcscf.mcscf_solver(ref_wfn)                                                                                                                                                    
      File "/Users/jeffschriber/src/psi4_debug_install/lib//psi4/driver/procedures/mcscf/mcscf_solver.py", line 227, in mcscf_solver                                                     
        total_step = diis_obj.extrapolate()                                                                                                                                              
      File "/Users/jeffschriber/src/psi4_debug_install/lib//psi4/driver/procedures/mcscf/diis_helper.py", line 98, in extrapolate                                                        
        eigvals, eigvecs = np.linalg.eigh(B)                                                                                                                                             
      File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1246, in eigh                                                                                           
    w, vt = gufunc(a, signature=signature, extobj=extobj)                                                                                                                            
      File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 96, in _raise_linalgerror_eigenvalues_nonconvergence                                                    
    raise LinAlgError("Eigenvalues did not converge")                                                                                                                                
                                                                                                                                                                                     
    LinAlgError: Eigenvalues did not converge

**Comment by jeffschriber** [comment]
It seems that the remaining differences result from small changes in the integrals and not in any forte-related procedure. I've updated the failing test cases to reflect this.
