### ISSUE TITLE
No explicit/top-level license/copyright

### ISSUE THREAD

**Issue by mbanck** [evangelistalab/forte#12]
Some of the forte files in src/ (and src/mini-boost in general, but that is external code I think) have a GPLv2+ license, but at least half of the files have no copyright or license header and there is no copyright/license statement in README.md or a separate COPYING.md/LICENSE.md

**Comment by fevangelista** [comment]
Thanks for raising this issue. It was addressed in commit de336c35dbd28ac40f92faf976e2944349dfc122.
