### ISSUE TITLE
New SemiCanonicalize class not working for total spin > 0

### ISSUE THREAD

**Issue by jeffschriber** [evangelistalab/forte#14]
Proceed with caution until this is resolved

**Comment by jeffschriber** [comment]
Closing, there is no issue with the semicanonicalize class. Make sure you input Ms = 0 solutions only, or be prepared for unrestricted formalisms.

**Comment by fevangelista** [comment]
Thanks for checking this one. Perhaps it would be a good idea to add a test case and also try a case with negative Ms.
