### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#15]

**Comment by loriab** [comment]
The `sed`s are [here](https://github.com/psi4/psi4/pull/690) for Mac. Watch out on that last one, as it's set up for C++ files, not Py. [This](https://www.gnu.org/licenses/gpl-howto.en.html) is what we were trying to follow.

**Comment by fevangelista** [comment]
Addressed by commit 6bf3e0b10de339b654337a374c1768c56625a4ea.
