### ISSUE TITLE
Forte Compilation Error due to DF RMP2

### ISSUE THREAD

**Issue by JonathonMisiewicz** [evangelistalab/forte#288]
Forte doesn't compile for me, even after following the [readme](https://github.com/evangelistalab/forte/blob/master/README.md) instructions for `setup.py`. I compile successfully upon commenting out the declarations and definitions and calls to
```
    /// Build OO part of DF-UMP2 1-RDM
    void compute_df_ump2_1rdm_oo(ambit::BlockedTensor& D1);
    /// Build VV part of DF-UMP2 1-RDM
    void compute_df_ump2_1rdm_vv(ambit::BlockedTensor& D1);
    /// Build OO part of DF-RMP2 1-RDM
    void compute_df_rmp2_1rdm_oo(ambit::BlockedTensor& D1);
    /// Build VV part of DF-RMP2 1-RDM
    void compute_df_rmp2_1rdm_vv(ambit::BlockedTensor& D1);
```

The offending functions may be found in `mp2_nos.h` and `mp2_nos.cc`. Error message is
```
ImportError: dlopen(/Users/jonathonmisiewicz/forte/forte/_forte.cpython-37m-darwin.so, 2): Symbol not found: __ZNSt3__113__invokable_rIvRZN5forte7MP2_NOS23compute_df_rmp2_1rdm_ooERN5ambit13BlockedTensorEE4$_15JRKNS_6vectorImNS_9allocatorImEEEERdEE5valueE
  Referenced from: /Users/jonathonmisiewicz/forte/forte/_forte.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/jonathonmisiewicz/forte/forte/_forte.cpython-37m-darwin.so
```

Compilation fail happens even on pre-DIIS refactor and L2 Psi.

**Comment by JonathonMisiewicz** [comment]
Including [an iterate statement like this](https://github.com/evangelistalab/forte/blob/master/forte/orbital-helpers/mp2_nos.cc#L499-L501) is sufficient to make the crash occur, even when the actual contents of the function signature are commented out.

**Comment by JonathonMisiewicz** [comment]
Removing `default(none) shared(Jab)` will also cure the import problem, though I'm puzzled as to _why_.

**Comment by JonathonMisiewicz** [comment]
I've experimented with a mockup of `ambit::Tensor`, and I can reproduce this so long as I call _any_ method of my `MockTensor` that takes a function argument. While it's slightly ugly, I think that being shared by default (removing the clauses I mentioned in my previous post) is our best option.

**Comment by lcyyork** [comment]
This is strange. The code compiles and runs for me on a linux machine.
