### ISSUE TITLE
Future: test case ACI-MRCISD-2 is bound to break

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#31]
Cannot yet predict the future, but I know that once changes to the Be basis introduced by pull request psi4/psi4#728 come into effect, the SCF and CI energies will change slightly in test case ACI-MRCISD-2. Once psi4/psi4#728 propagates to Travis update test case.

**Comment by jeffschriber** [comment]
I can manually use the older version of the basis to keep the test intact. I'll pull the new changes to Psi and see if other test cases fail.

**Comment by jeffschriber** [comment]
The test case fails with the updated basis, works with manual input of the old one.
