### ISSUE TITLE
Generating cube files from Forte wavefunctions

### ISSUE THREAD

**Issue by jeffschriber** [evangelistalab/forte#343]
Hello!

I'm interested in plotting orbitals with Forte, and most of my (quite old) inputs no longer seem to work. The ends of my inputs look something like (I'm happy to post a runnable example if needed):
```
set forte {
active_space_solver  aci
rotate_mos                 [1,17,20]
frozen_docc               [4]
restricted_docc         [9]
active                          [4]
orbital_type                local
sigma                          0.0001
multiplicity                 1
nroot                           1
}
scf_e, scf_wfn = energy('scf', return_wfn=True) 
aci_e, aci_wfn = energy('forte', ref_wfn=wfn, return_wfn=True)
forte.utils.psi4_cubeprop(aci_wfn, orbs=[14,15,16,17])
```
While I get correct energies, it seems that `aci_wfn` and `scf_wfn` have identical Ca matrices (this I've checked), and in plotting the orbitals, they correspondingly aren't localized or resorted. It looks like the new driver doesn't modify-then-return a psi wave function, probably for good reason. Is there some new way to generate cube files from orbitals that have been modified by Forte? This is important for things like: ensuring that active spaces are correctly chosen, making various density plots from NOs, etc. I'd prefer not to do the orbital transformations manually, unless the API makes that part very simple. 

If there are some changes to the the code that are needed to achieve this, I'm happy to work on that.

**Comment by lcyyork** [comment]
Hi Jeff, the following seems to work for me.

```
import forte
memory 1 gb

molecule butadiene{
0 1
H  1.080977 -2.558832  0.000000
H -1.080977  2.558832  0.000000
H  2.103773 -1.017723  0.000000
H -2.103773  1.017723  0.000000
H -0.973565 -1.219040  0.000000
H  0.973565  1.219040  0.000000
C  0.000000  0.728881  0.000000
C  0.000000 -0.728881  0.000000
C  1.117962 -1.474815  0.000000
C -1.117962  1.474815  0.000000
symmetry c1
}

set {
  reference      rhf
  scf_type       df
  basis          def2-tzvp
  df_basis_scf   def2-universal-jkfit
  df_basis_mp2   def2-universal-jkfit
  e_convergence  10
  d_convergence  12
  maxiter        100
  cubeprop_orbitals [14,15,16,20]  # have to say 20 here in latest psi4
}
Escf, wfn = energy('scf', return_wfn=True)
compare_values(r_scf, Escf, 8, "SCF energy")

set forte {
int_type df
active_space_solver fci
rotate_mos [1,17,20]
frozen_docc [4]
restricted_docc [9]
active [4]
orbital_type local
localize_space [13,16]
}
e, wfn = energy('forte', ref_wfn=wfn, return_wfn=True)
cubeprop(wfn)
```

**Comment by jeffschriber** [comment]
Thanks York! Yes your input also works for me. I think my issue was that I was requesting the orbitals [14,15,16,17], not realizing that psi still needs the original indexing. The lack of localization on my end also seemed to be related to obsolete keywords. I've also been playing with AVAS to get the active orbitals we need, and that's been working nicely (but it does need the sequential indexing for plotting, fine by us).
