### ISSUE TITLE
make_active_space_ints produces segmentation fault

### ISSUE THREAD

**Issue by brianz98** [evangelistalab/forte#394]
The `forte.utils` function `prepare_ints_rdms` and `prepare_forte_objects` both result in a segmentation fault. A minimal example is given below. As limited information is given, simple print-debugging on the Python side points to `active_space_integrals.cc::make_active_space_ints` being the culprit.

```
import forte
import forte.utils

molecule o2{
0 1
N
N 1 1.1
}

set globals{
    basis          cc-pvdz
    scf_type       pk
    e_convergence  12
    reference      rhf
}        

set forte{
    job_type            mcscf_two_step
    active_space_solver fci
    restricted_docc     [2,0,0,0,0,2,0,0]
    active              [1,0,1,1,0,1,1,1]
    mcscf_reference     True
    }

E, wfn = energy('forte', return_wfn=True)

mo_spaces = {'RESTRICTED_DOCC': [2,0,0,0,0,2,0,0], 'ACTIVE': [1,0,1,1,0,1,1,1]}
res = forte.utils.prepare_ints_rdms(wfn, mo_spaces)
```
This produces 
```
(forte) dsrg_sandbox $ psi4 ints.dat
INFO:psi4.driver.driver:Return energy(): -109.09022707213609
zsh: segmentation fault  psi4 ints.dat
```

**Comment by lcyyork** [comment]
This is because mcscf does not use ForteIntegrals "get" functionalities other than jk.

**Comment by brianz98** [comment]
> This is because mcscf does not use ForteIntegrals "get" functionalities other than jk.

Is there currently a way to obtain Forte mcscf rdms and integrals on the Python side? Many of the new modules are still sparsely documented.

**Comment by brianz98** [comment]
Asking before I start on a PR and cause further code duplication..
