### ISSUE TITLE
Travis fails

### ISSUE THREAD

**Issue by jeffschriber** [evangelistalab/forte#42]
Travis is unable to compile forte. It fails with: 

    /home/travis/build/evangelistalab/forte/src/integrals/diskdf_integrals.cc:38:10: fatal error: 
    'psi4/libthce/lreri.h' file not found

I'm not too sure why this happens, I can successfully run an compile on my laptop using the newest version of Psi.

**Comment by fevangelista** [comment]
I think perhaps libTHCE was removed from Psi4. That's going to be a bit of a problem...

**Comment by jeffschriber** [comment]
That seems to be the case. I'm sure if I did a new psi4 clone, I'd get the same error

**Comment by fevangelista** [comment]
One way to temporarily avoid the problem is to tell Travis to checkout an older version of psi4. If you are going to try to do that I advise setting up a new branch.
