### ISSUE TITLE
Deboost Forte

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#5]
Soon Boost will be removed from Psi4 (see https://github.com/psi4/psi4/issues/450).  This change will break Forte since it uses a few boost libraries.  Moving Boost should be simple for the most part, but will need to find a replacement for the ODE integrators, or find a way to include parts of Boost in Forte.

**Comment by loriab** [comment]
If it's any help, @robertodr & PCMSolver (https://github.com/PCMSolver/pcmsolver) I believe use header-only Boost libraries. If total deboosting is impossible, that's a model.

**Comment by kannon92** [comment]
@fevangelista I have been working on adding MPI to forte over the last few weeks.  Could I merge this branch before you make these changes?  I made quite a bit of changes throughout the code, so I really don't have to spend a few hours solving merge conflicts once this change is made.  

I have been periodically checking the code to make sure that if you don't have MPI/Global Arrays, the code can compile fine without it.

**Comment by fevangelista** [comment]
Sounds like a good idea to merge the branch.  Can you please run tests before merging just to make sure all test pass and then merge?  I think that we might go with headers-only boost as suggested by @loriab before removing boost completely.

**Comment by robertodr** [comment]
@fevangelista FYI the ODE library is headers-only. In principle also available standalone: https://github.com/headmyshoulder/odeint-v2 The source code seems enmeshed with Boost stuff though...

**Comment by loriab** [comment]
Found this scary depiction of the Boost dependency structure. Another place to look for alternatives is GSL (https://www.gnu.org/software/gsl/). We just got rid of that dependency in CheMPS2, but it'd be easier for you to manage than Boost, I suspect.

![boostdep](https://cloud.githubusercontent.com/assets/2314730/17519699/0735c4a2-5e1b-11e6-95ec-8875a73f0254.png)

**Comment by robertodr** [comment]
Scary chart indeed :fearful: Odeint doesn't seem to be anywhere on that, though.

**Comment by loriab** [comment]
True, that was a general scare tactic. :-)

Here's more Bessel Function links, if those are still in discussion: 
* http://dlmf.nist.gov/10.77 
* https://www.gnu.org/software/gsl/manual/html_node/Bessel-Functions.html
* https://github.com/valandil/complex_bessel

**Comment by fevangelista** [comment]
Thanks @loriab!  Boost is a real mess of dependencies.  So I made a header only mini-boost (a euphemism really) but have not deployed yet because of the recent merge with our MPI branch.

**Comment by robertodr** [comment]
@fevangelista FYI Autocmake has a module that takes care of [Boost](http://autocmake.readthedocs.io/en/latest/module-reference.html#boost-cmake) You can switch between header-only and compiled library+headers mode. The behavior is much like the one in the soon-to-be-gone Boost module in Psi4 current CMake system. Unfortunately, when asking for header-only **all** headers are unpacked. That is due to the scary chart @loriab posted.

Disclaimer: I wrote that module for Autocmake :smiley:

**Comment by loriab** [comment]
If you'd like to prepare to use Autocmake without wholly committing yet, a model could be copying in certain files like https://github.com/loriab/libint1/tree/master/cmake then including them in top-level CMakeLists.txt like https://github.com/loriab/libint1/blob/master/CMakeLists.txt#L10-L11 .

**Comment by fevangelista** [comment]
@robertodr and @loriab: Thanks for the suggestion.  I am not very familiar with Autocmake but if it will simplify things when we have completely de-boosted forte I'll take a look.  Right now commit af7b9a1a99b6943783eafe6186dd9883e5308e34 adds the minimal boost headers required by forte.  The problem with the scary chart is that already a single boost library requires a lot of ancillary headers.  So we will have to remove all dependencies to close this issue definitively.

**Comment by jeffschriber** [comment]
Can we finally close this issue now?
