### ISSUE TITLE
Fail to compile on cluster

### ISSUE THREAD

**Issue by kannon92** [evangelistalab/forte#8]
Hey everybody,

I am not able to compile the code on both my mac and the linux box.  I get this error:

    mini-boost/boost/numeric/odeint.hpp:74:63: fatal error:      
    boost/numeric/odeint/integrate/max_step_checker.hpp: No such file or directory
    #include <boost/numeric/odeint/integrate/max_step_checker.hpp>

**Comment by jeffschriber** [comment]
Try to re-run the setup script

**Comment by kannon92** [comment]
Thank you, Jeff.  Everything works now.
