### ISSUE TITLE
Changes to forte to make sure it works with new PSI4CMAKE

### ISSUE THREAD

**Issue by kannon92** [evangelistalab/forte#9]
I think we should maybe pick a time to transfer forte to the new PSI4.  I think we probably just have to make sure that we switch all shared_ptrs to be the standard.  And make sure to change SharedMatrix if we put in the full type name.  

We should do this once ambit is completed merged into the new cmake rewrite.

**Comment by fevangelista** [comment]
Agreed!  We were planning on working on this early October when (hopefully) most bugs from the new cmake rewrite are squished.

**Comment by fevangelista** [comment]
Addressed by merge.
